[channel]
generator = utipod
xmlbase = http://174.89.235.81:8080/UC5aNPmKYwbudeNngDMTY3lw
description = "BNN Bloomberg is Canada's only television service devoted exclusively to business and finance news with wall-to-wall coverage of the markets."
title = "BNN Bloomberg"
link = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw

[channel "image"]
url = https://yt3.googleusercontent.com/ytc/AL5GRJUcfMPvBrk_UF9EdM2LmCxBNKKQ6NIfLTj2gsd7CA=s0

