[item]
guid = 0kSE1V0hNyc
title = "Two indicators of inflation | Chart Attack"
description = "BNN Bloomberg's Amber Kanwar looks at a chart and talks about the two common indicators of inflation: CPI and PCE.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=0kSE1V0hNyc
category = "News & Politics"
pubdate = Fri, 24 Feb 2023 00:00:00 -0000
enclosure = 0kSE1V0hNyc.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/0kSE1V0hNyc/maxresdefault.jpg

