[item]
guid = 18JhH-eLDlg
title = "MoneyTalk - Big Tech Layoffs"
description = "Vitali Mossounov, Global Technology Analyst at TDAM returns to MoneyTalk to discuss big tech layoffs\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=18JhH-eLDlg
category = "News & Politics"
pubdate = Thu, 16 Feb 2023 00:00:00 -0000
enclosure = 18JhH-eLDlg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/18JhH-eLDlg/maxresdefault.jpg

