[item]
guid = 24GIWRU8Fjw
title = "Silicon Valley Bank collapse stemmed from a liquidity crisis"
description = "Robert Pozen, senior lecturer at MIT Sloan School of Management and former chairman of the SEC's advisory committee on financial reporting, joins BNN Bloomberg to discuss the Silicon Valley Bank fallout. He says the problem was the mismatch between short term deposits and the current fair market value of those longer term assets.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=24GIWRU8Fjw
category = "News & Politics"
pubdate = Mon, 13 Mar 2023 00:00:00 -0000
enclosure = 24GIWRU8Fjw.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/24GIWRU8Fjw/maxresdefault.jpg

