[item]
guid = 2nOHsV0BL3c
title = "There won't be an economic recovery without some kind of price"
description = "Nik Nanos, chief data scientist and founder of Nanos Research Group, joins BNN Bloomberg to talk about how the collapse of Silicon Valley Bank could affect consumer confidence in Canada. Nanos says the consumer sentiment index started to trend upward in the last four weeks and the last thing it needs is any kind of uncertainty or a 'contagion' effect.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=2nOHsV0BL3c
category = "News & Politics"
pubdate = Mon, 13 Mar 2023 00:00:00 -0000
enclosure = 2nOHsV0BL3c.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/2nOHsV0BL3c/maxresdefault.jpg

