[item]
guid = 8KnzfavMg4Y
title = "Avoid stocks, we haven't seen the lows, barbell between treasury bills, long bonds"
description = "David Rosenberg, founder and president of Rosenberg Research, joins BNN Bloomberg for his view on the markets as the BoC and the U.S. Fed divergence occurs. Rosenberg expects a recession in the upcoming quarters. He adds an earnings recession is underway, advising investors to stay away from the equities market and instead focus on a fixed income.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=8KnzfavMg4Y
category = "News & Politics"
pubdate = Thu, 09 Mar 2023 00:00:00 -0000
enclosure = 8KnzfavMg4Y.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/8KnzfavMg4Y/maxresdefault.jpg

