[item]
guid = B8hRhIg2PTU
title = "How to survive a layoff mid-career"
description = "Bruce Sellery, CEO of Credit Canada joins BNN Bloomberg to discuss how one can prepare for and overcome sudden job loss. He says to 'fill the well before you're thirsty' and that there are ways to prepare for a layoff financially, practically and emotionally.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=B8hRhIg2PTU
category = "News & Politics"
pubdate = Thu, 16 Feb 2023 00:00:00 -0000
enclosure = B8hRhIg2PTU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/B8hRhIg2PTU/maxresdefault.jpg

