[item]
guid = fV_DBT1iEA0
title = "Canadian data is showing a disinflationary trend at the beginning of this year: Dominique Lapointe"
description = "Dominique Lapointe, global macro strategist at Manulife Investment Management, joins BNN Bloomberg to discuss Canada's inflation rate that slow to 5.9 per cent in January. He says retail consumption on nominal basis is still miles away from pre-pandemic trends.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=fV_DBT1iEA0
category = "News & Politics"
pubdate = Tue, 21 Feb 2023 00:00:00 -0000
enclosure = fV_DBT1iEA0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/fV_DBT1iEA0/maxresdefault.webp

