[item]
guid = j_riExS8akg
title = "Nordstrom has stuggled to be profitable in Canada since 2014"
description = "David Swartz, equity analyst at Morningstar Research Services, joins BNN Bloomberg to discuss Nordstrom's announcement that it will wind down its Canadian operations. He says many stores, such as the Nordstrom in Vancouver, relied on tourism, and that hurt sales during the pandemic.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=j_riExS8akg
category = "News & Politics"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = j_riExS8akg.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/j_riExS8akg/maxresdefault.jpg

