[item]
guid = JrsXNpJN3e4
title = "There's reason to be a little bit optimistic about interest rates"
description = "Christine Tan, portfolio manager at SLGI Asset Management Inc., joins BNN Bloomberg to discuss her outlook for the Fed and the Bank of Canada's tightening paths.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=JrsXNpJN3e4
category = "News & Politics"
pubdate = Tue, 21 Feb 2023 00:00:00 -0000
enclosure = JrsXNpJN3e4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/JrsXNpJN3e4/maxresdefault.jpg

