[item]
guid = jtximY3vJ7A
title = "Gasoline price outlook: Oil price drop"
description = "Roger McKnight, chief petroleum analyst at En-Pro International, joins BNN Bloomberg to give his gasoline price outlook for the week ahead. McKnight noted that 'over the short term pump prices are under downward pressure as crude oil and gasoline inventories continue to build.' McKnight added that there's no specific timeline on when this will change.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=jtximY3vJ7A
category = "News & Politics"
pubdate = Fri, 17 Feb 2023 00:00:00 -0000
enclosure = jtximY3vJ7A.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/jtximY3vJ7A/maxresdefault.jpg

