[item]
guid = kjbs4w6ATLs
title = "High dividend stocks: Hot Picks"
description = "Iman Brivanlou, managing director of income equities at TCW, joins BNN Bloomberg for his three top picks in dividend stocks. Brivanlou says that dividend stocks are attractive right now as they can provide protection until the markets rebound. He likes Ares Capital, Alexandria Real Estate Equities and M&T Bank.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=kjbs4w6ATLs
category = "News & Politics"
pubdate = Thu, 02 Mar 2023 00:00:00 -0000
enclosure = kjbs4w6ATLs.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/kjbs4w6ATLs/maxresdefault.jpg

