[item]
guid = laLC8xjQzS0
title = "Eventually the U.S. labour market will feel pain of higher interest rates"
description = "Thomas Tzitzouris, VP and director of fixed income research at Strategas, joins BNN Bloomberg to break down his recent fixed income report.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=laLC8xjQzS0
category = "News & Politics"
pubdate = Thu, 02 Mar 2023 00:00:00 -0000
enclosure = laLC8xjQzS0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/laLC8xjQzS0/maxresdefault.jpg

