[item]
guid = NO4T0vIPnfA
title = "More risk of a short pullback of jobs"
description = "Sal Guatieri, director and senior economist at BMO Capital Markets, joins BNN Bloomberg to share his reaction to the BoC's rate pause and comments earlier in the week. He looks ahead to the jobs data expected in the U.S. and Canada at the end of the week, and says there is good chance of a pullback in jobs numbers from January.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=NO4T0vIPnfA
category = "News & Politics"
pubdate = Thu, 09 Mar 2023 00:00:00 -0000
enclosure = NO4T0vIPnfA.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/NO4T0vIPnfA/maxresdefault.jpg

