[item]
guid = NOfJGruPFyk
title = "Taking Stock - Millennial's are up to their necks in debt"
description = "As rates stay high, what's the best strategy on mortgage renewals? Guest: Janet Gray, financial plann and James Laird, co-CEO, Ratehub.ca\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=NOfJGruPFyk
category = "News & Politics"
pubdate = Sat, 18 Feb 2023 00:00:00 -0000
enclosure = NOfJGruPFyk.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/NOfJGruPFyk/maxresdefault.jpg

