[item]
guid = sr7JHXbh-qQ
title = "The first half of the year will have a lot of volatility"
description = "Brianne Gardner, wealth manager and investment advisor at Velocity Investment Partners with Raymond James, joins BNN Bloomberg to talk about her outlook for markets. She says the fear of missing out is driving the market right now, but investors should be careful.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=sr7JHXbh-qQ
category = "News & Politics"
pubdate = Fri, 17 Feb 2023 00:00:00 -0000
enclosure = sr7JHXbh-qQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/sr7JHXbh-qQ/maxresdefault.webp

