[item]
guid = u-4EZVRHwHI
title = "Economy can pick up when demand is back"
description = "Kim Caughey Forrest, founder and chief investment officer at Bokeh Capital Partners, joins BNN Bloomberg to discuss the market. Forrest says there is a push-pull between the idea that the FED is close to done versus the FED is going to hike higher and remain high longer. 'Then there is a small portion of people thinking that the Fed has already moved too far and too fast and we are slipping into a recession.'\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=u-4EZVRHwHI
category = "News & Politics"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = u-4EZVRHwHI.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/u-4EZVRHwHI/maxresdefault.webp

