[item]
guid = Uan7gzMHuX4
title = "Reasons to buy the U.S. health care sector and EV industry"
description = "David Nelson, chief strategist at Belpointe Asset Management, joins BNN Bloomberg for his view on the stock market amid China's reopening. Nelson likes names the EV industry and is bullish on Albemarle Corporation. He also likes Health Care and advises investors to look at XLV.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=Uan7gzMHuX4
category = "News & Politics"
pubdate = Wed, 01 Mar 2023 00:00:00 -0000
enclosure = Uan7gzMHuX4.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/Uan7gzMHuX4/maxresdefault.webp

