[item]
guid = uGtZpqgz5S0
title = "Looks like we're in a market volatility regime in 2023 and 2024"
description = "Jeff Weniger, head of equity strategy at WisdomTree Asset Management, joins BNN Bloomberg to discuss why he thinks market volatility is heading higher. He also says the freeze-up in U.S. housing is a key driver for labor market deterioration.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=uGtZpqgz5S0
category = "News & Politics"
pubdate = Wed, 01 Mar 2023 00:00:00 -0000
enclosure = uGtZpqgz5S0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/uGtZpqgz5S0/maxresdefault.jpg

