[item]
guid = XGCbW0sDvew
title = "Uranium will see repricing soon as the demand continues to grow"
description = "Whitney George, CEO of Sprott Inc., joins BNN Bloomberg to discuss the company's energy transition and his outlook for precious metals. He says Sprott Physical Uranium Trust has allowed the company to enter the energy transition space.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=XGCbW0sDvew
category = "News & Politics"
pubdate = Tue, 28 Feb 2023 00:00:00 -0000
enclosure = XGCbW0sDvew.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/XGCbW0sDvew/maxresdefault.jpg

