[item]
guid = XnkO6CzxYtQ
title = "Taking Stock - Private sector and public sector"
description = "Guest: Why is the government so bad at big projects? Lisa Raitt, CIBC Capital Markets, former leader of the Conservative Party of Canada.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=XnkO6CzxYtQ
category = "News & Politics"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = XnkO6CzxYtQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/XnkO6CzxYtQ/maxresdefault.jpg

