[item]
guid = xpEM-S4aA0I
title = "Taking Stock - A special look at the business of the government"
description = "Guest: The public sector is a vital part of the delivery of government service – so how is ours? Michael Wernick, former clerk of the Privy Council.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=xpEM-S4aA0I
category = "News & Politics"
pubdate = Fri, 03 Mar 2023 00:00:00 -0000
enclosure = xpEM-S4aA0I.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/xpEM-S4aA0I/maxresdefault.jpg

