[item]
guid = xrz_SKMz5ZU
title = "TSX is well positioned for continued outperformance, versus the U.S."
description = "Brian Belski, chief market strategist at BMO, joins BNN Bloomberg to discuss the market. Belski tells BNN Bloomberg January ended off on a strong note for the U.S stocks, but that doesn’t mean things remained the same throughout this month. He added that the TSX is well positioned for continued outperformance, versus the U.S and other global markets.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=xrz_SKMz5ZU
category = "News & Politics"
pubdate = Tue, 28 Feb 2023 00:00:00 -0000
enclosure = xrz_SKMz5ZU.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/xrz_SKMz5ZU/maxresdefault.jpg

