[item]
guid = YQGPypPcjpE
title = "Taking Stock - Shopify is innovating how it rewards employees"
description = "Shopify is innovating how it rewards employees – what other businesses could learn. Stephen Harrington, partner of Human Capital, Deloitte Canada\n \nTakeaway: Women everywhere can call it a victory when we no long need “international Women’s day” – for now, it’s a reminder of how far from the goal we are.\n\nSubscribe to BNN Bloomberg to watch more videos: https://www.youtube.com/BNNBloomberg\n\nConnect with BNN Bloomberg: \nFor the latest news visit: https://www.bnnbloomberg.ca\nFor a full video offering visit BNN Bloomberg: https://www.bnnbloomberg.ca/video\nBNN Bloomberg on Facebook: https://www.facebook.com/BNNBloomberg \nBNN Bloomberg on Twitter: https://twitter.com/bnnbloomberg \nBNN Bloomberg on Instagram: https://www.instagram.com/bnnbloomberg \nBNN Bloomberg on LinkedIn: https://www.linkedin.com/company/bnn-bloomberg\n--\nBNN Bloomberg is Canada’s only TV service devoted exclusively to business, finance and the markets."
author = BNN Bloomberg
source = https://www.youtube.com/channel/UC5aNPmKYwbudeNngDMTY3lw
link = https://www.youtube.com/watch?v=YQGPypPcjpE
category = "News & Politics"
pubdate = Sat, 11 Mar 2023 00:00:00 -0000
enclosure = YQGPypPcjpE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/YQGPypPcjpE/maxresdefault.jpg

